ecommerce/customer/urls.py
from django.urls import path
from .views import *

app_name = 'customer'
urlpatterns = [
    path('cart/', cart_home, name='cart_list'),
    path('cart/add/<int:id>', cart_add, name='cart_add'),
    path('cart/remove/<int:id>', cart_remove, name='cart_remove'),
    path('cart/delete/<int:id>', cart_delete, name='cart_delete'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls')),
    path('', include('user.urls')),
    path('accounts/', include('accounts.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='user_home'),
    path('about/', about, name='user_about'),
    path('contact/', contact, name='user_contact_two'),
    path('seed-user/', seed_user, name='user_seed_user'),
]

ecommerce/customer/models.py
from django.db import models

# Create your models here.

ecommerce/customer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from administrator.models import *
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def cart_home(request):
    context = {
        'object_list': Cart.objects.filter(user=request.user).select_related('product'),
    }
    return render(request, 'customer/cart/list.html', context)


@login_required
def cart_add(request, id):
    product = get_object_or_404(Product, id=id)
    cart = Cart.objects.filter(user=request.user, product=product).first()
    if not cart:
        cart = Cart.objects.create(user=request.user, product=product, quantity=1)
        return redirect('customer:cart_list')
    
    if cart.quantity < 5:
        cart.quantity += 1
        cart.save()
        return redirect('customer:cart_list')


@login_required
def cart_remove(request, id):
    cart = get_object_or_404(Cart, id=id, user=request.user)
    
    if cart.quantity > 1:
        cart.quantity -= 1
        cart.save()
        return redirect('customer:cart_list')
    
    cart.delete()
    return redirect('customer:cart_list')


@login_required
def cart_delete(request, id):
    cart = get_object_or_404(Cart, id=id, user=request.user)
    cart.delete()
    return redirect('customer:cart_list')

ecommerce/customer/templates/customer/cart/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1 class="text-center">Cart</h1>
    <div class="container my-2">
        <table class="table table-striped">
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for i in object_list %}
            <tr>
                <td>{{ i.product.name }}</td>
                <td>{{ i.product.price }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{% url 'customer:cart_remove' id=i.id %}" class="btn btn-danger">-</a>
                        <button class="btn btn-primary">{{ i.quantity }}</button>
                        <a href="{% url 'customer:cart_add' id=i.product.id %}" class="btn btn-success">+</a>
                    </div>
                </td>
                <td>
                    <a href="{% url 'customer:cart_delete' id=i.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}
    